# Generated by Django 3.1.5 on 2021-01-25 11:42

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210123_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='files',
            field=models.FileField(blank=True, upload_to='upload/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'pdf', 'doc', 'docx', 'jpg', 'xlsx', 'xls']), config.validators.file_size], verbose_name='Файл'),
        ),
    ]
