# Generated by Django 3.1.5 on 2021-01-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
