# Generated by Django 3.1.5 on 2021-01-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_temporarybanip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryBanIp',
        ),
    ]
