# Generated by Django 3.1.5 on 2021-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="source",
            field=models.URLField(blank=True, verbose_name="Джерело"),
        ),
    ]
